//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::groups::Entity as Groups;
pub use super::sessions::Entity as Sessions;
pub use super::tickets::Entity as Tickets;
pub use super::users::Entity as Users;
